######################################################################
#
# File name : tb_ip_clk_wiz_wave.do
# Created on: Wed Oct 25 18:40:38 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
