create_clock -period 20.000 -name sys_clk [get_ports sys_clk] 

set_property IOSTANDARD LVCMOS33 [get_ports {key[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN U18 [get_ports sys_clk]
set_property PACKAGE_PIN N16 [get_ports rst]
set_property PACKAGE_PIN L14 [get_ports {key[0]}]
set_property PACKAGE_PIN K16 [get_ports {key[1]}]
set_property PACKAGE_PIN H15 [get_ports {led[0]}]
set_property PACKAGE_PIN L15 [get_ports {led[1]}]
