set_property SRC_FILE_INFO {cfile:G:/FPGA/ip_2port_ram/vivado_prj/ip_2port_ram/ip_2port_ram.srcs/constrs_1/new/ip_2port_ram.xdc rfile:../../../ip_2port_ram.srcs/constrs_1/new/ip_2port_ram.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports clk]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS33} [get_ports rst_n]
