set_property PACKAGE_PIN L14 [get_ports key]
set_property PACKAGE_PIN H15 [get_ports led]
set_property DRIVE 12 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports key]
